//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebcreteAPIExplorer.WebcreteAPI2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.concretego.com/", ConfigurationName="WebcreteAPI2.WebcreteAPISoap")]
    public interface WebcreteAPISoap {
        
        // CODEGEN: Generating message contract since message GetPublicKeyResponse has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/GetPublicKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebcreteAPIExplorer.WebcreteAPI2.GetPublicKeyResponse GetPublicKey(WebcreteAPIExplorer.WebcreteAPI2.GetPublicKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/GetPublicKey", ReplyAction="*")]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI2.GetPublicKeyResponse> GetPublicKeyAsync(WebcreteAPIExplorer.WebcreteAPI2.GetPublicKeyRequest request);
        
        // CODEGEN: Generating message contract since message LoginRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebcreteAPIExplorer.WebcreteAPI2.LoginResponse Login(WebcreteAPIExplorer.WebcreteAPI2.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI2.LoginResponse> LoginAsync(WebcreteAPIExplorer.WebcreteAPI2.LoginRequest request);
        
        // CODEGEN: Generating message contract since message ProcessRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/ProcessRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebcreteAPIExplorer.WebcreteAPI2.ProcessRequestResponse ProcessRequest(WebcreteAPIExplorer.WebcreteAPI2.ProcessRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/ProcessRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI2.ProcessRequestResponse> ProcessRequestAsync(WebcreteAPIExplorer.WebcreteAPI2.ProcessRequestRequest request);
        
        // CODEGEN: Generating message contract since message LogoutRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebcreteAPIExplorer.WebcreteAPI2.LogoutResponse Logout(WebcreteAPIExplorer.WebcreteAPI2.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI2.LogoutResponse> LogoutAsync(WebcreteAPIExplorer.WebcreteAPI2.LogoutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.concretego.com/")]
    public partial class TicketHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid ticketField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
                this.RaisePropertyChanged("ticket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPublicKey", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class GetPublicKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public string appID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=1)]
        public string apiKey;
        
        public GetPublicKeyRequest() {
        }
        
        public GetPublicKeyRequest(string appID, string apiKey) {
            this.appID = appID;
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPublicKeyResponse", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class GetPublicKeyResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.concretego.com/")]
        public WebcreteAPIExplorer.WebcreteAPI2.TicketHeader TicketHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public string GetPublicKeyResult;
        
        public GetPublicKeyResponse() {
        }
        
        public GetPublicKeyResponse(WebcreteAPIExplorer.WebcreteAPI2.TicketHeader TicketHeader, string GetPublicKeyResult) {
            this.TicketHeader = TicketHeader;
            this.GetPublicKeyResult = GetPublicKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.concretego.com/")]
        public WebcreteAPIExplorer.WebcreteAPI2.TicketHeader TicketHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] password;
        
        public LoginRequest() {
        }
        
        public LoginRequest(WebcreteAPIExplorer.WebcreteAPI2.TicketHeader TicketHeader, string userName, byte[] password) {
            this.TicketHeader = TicketHeader;
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public bool LoginResult;
        
        public LoginResponse() {
        }
        
        public LoginResponse(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessRequest", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class ProcessRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.concretego.com/")]
        public WebcreteAPIExplorer.WebcreteAPI2.TicketHeader TicketHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public string request;
        
        public ProcessRequestRequest() {
        }
        
        public ProcessRequestRequest(WebcreteAPIExplorer.WebcreteAPI2.TicketHeader TicketHeader, string request) {
            this.TicketHeader = TicketHeader;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessRequestResponse", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class ProcessRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public string ProcessRequestResult;
        
        public ProcessRequestResponse() {
        }
        
        public ProcessRequestResponse(string ProcessRequestResult) {
            this.ProcessRequestResult = ProcessRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Logout", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.concretego.com/")]
        public WebcreteAPIExplorer.WebcreteAPI2.TicketHeader TicketHeader;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(WebcreteAPIExplorer.WebcreteAPI2.TicketHeader TicketHeader) {
            this.TicketHeader = TicketHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogoutResponse", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public bool LogoutResult;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(bool LogoutResult) {
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebcreteAPISoapChannel : WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebcreteAPISoapClient : System.ServiceModel.ClientBase<WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap>, WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap {
        
        public WebcreteAPISoapClient() {
        }
        
        public WebcreteAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebcreteAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebcreteAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebcreteAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebcreteAPIExplorer.WebcreteAPI2.GetPublicKeyResponse WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap.GetPublicKey(WebcreteAPIExplorer.WebcreteAPI2.GetPublicKeyRequest request) {
            return base.Channel.GetPublicKey(request);
        }
        
        public WebcreteAPIExplorer.WebcreteAPI2.TicketHeader GetPublicKey(string appID, string apiKey, out string GetPublicKeyResult) {
            WebcreteAPIExplorer.WebcreteAPI2.GetPublicKeyRequest inValue = new WebcreteAPIExplorer.WebcreteAPI2.GetPublicKeyRequest();
            inValue.appID = appID;
            inValue.apiKey = apiKey;
            WebcreteAPIExplorer.WebcreteAPI2.GetPublicKeyResponse retVal = ((WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap)(this)).GetPublicKey(inValue);
            GetPublicKeyResult = retVal.GetPublicKeyResult;
            return retVal.TicketHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI2.GetPublicKeyResponse> WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap.GetPublicKeyAsync(WebcreteAPIExplorer.WebcreteAPI2.GetPublicKeyRequest request) {
            return base.Channel.GetPublicKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI2.GetPublicKeyResponse> GetPublicKeyAsync(string appID, string apiKey) {
            WebcreteAPIExplorer.WebcreteAPI2.GetPublicKeyRequest inValue = new WebcreteAPIExplorer.WebcreteAPI2.GetPublicKeyRequest();
            inValue.appID = appID;
            inValue.apiKey = apiKey;
            return ((WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap)(this)).GetPublicKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebcreteAPIExplorer.WebcreteAPI2.LoginResponse WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap.Login(WebcreteAPIExplorer.WebcreteAPI2.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(WebcreteAPIExplorer.WebcreteAPI2.TicketHeader TicketHeader, string userName, byte[] password) {
            WebcreteAPIExplorer.WebcreteAPI2.LoginRequest inValue = new WebcreteAPIExplorer.WebcreteAPI2.LoginRequest();
            inValue.TicketHeader = TicketHeader;
            inValue.userName = userName;
            inValue.password = password;
            WebcreteAPIExplorer.WebcreteAPI2.LoginResponse retVal = ((WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap)(this)).Login(inValue);
            return retVal.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI2.LoginResponse> WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap.LoginAsync(WebcreteAPIExplorer.WebcreteAPI2.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI2.LoginResponse> LoginAsync(WebcreteAPIExplorer.WebcreteAPI2.TicketHeader TicketHeader, string userName, byte[] password) {
            WebcreteAPIExplorer.WebcreteAPI2.LoginRequest inValue = new WebcreteAPIExplorer.WebcreteAPI2.LoginRequest();
            inValue.TicketHeader = TicketHeader;
            inValue.userName = userName;
            inValue.password = password;
            return ((WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebcreteAPIExplorer.WebcreteAPI2.ProcessRequestResponse WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap.ProcessRequest(WebcreteAPIExplorer.WebcreteAPI2.ProcessRequestRequest request) {
            return base.Channel.ProcessRequest(request);
        }
        
        public string ProcessRequest(WebcreteAPIExplorer.WebcreteAPI2.TicketHeader TicketHeader, string request) {
            WebcreteAPIExplorer.WebcreteAPI2.ProcessRequestRequest inValue = new WebcreteAPIExplorer.WebcreteAPI2.ProcessRequestRequest();
            inValue.TicketHeader = TicketHeader;
            inValue.request = request;
            WebcreteAPIExplorer.WebcreteAPI2.ProcessRequestResponse retVal = ((WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap)(this)).ProcessRequest(inValue);
            return retVal.ProcessRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI2.ProcessRequestResponse> WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap.ProcessRequestAsync(WebcreteAPIExplorer.WebcreteAPI2.ProcessRequestRequest request) {
            return base.Channel.ProcessRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI2.ProcessRequestResponse> ProcessRequestAsync(WebcreteAPIExplorer.WebcreteAPI2.TicketHeader TicketHeader, string request) {
            WebcreteAPIExplorer.WebcreteAPI2.ProcessRequestRequest inValue = new WebcreteAPIExplorer.WebcreteAPI2.ProcessRequestRequest();
            inValue.TicketHeader = TicketHeader;
            inValue.request = request;
            return ((WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap)(this)).ProcessRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebcreteAPIExplorer.WebcreteAPI2.LogoutResponse WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap.Logout(WebcreteAPIExplorer.WebcreteAPI2.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public bool Logout(WebcreteAPIExplorer.WebcreteAPI2.TicketHeader TicketHeader) {
            WebcreteAPIExplorer.WebcreteAPI2.LogoutRequest inValue = new WebcreteAPIExplorer.WebcreteAPI2.LogoutRequest();
            inValue.TicketHeader = TicketHeader;
            WebcreteAPIExplorer.WebcreteAPI2.LogoutResponse retVal = ((WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap)(this)).Logout(inValue);
            return retVal.LogoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI2.LogoutResponse> WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap.LogoutAsync(WebcreteAPIExplorer.WebcreteAPI2.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI2.LogoutResponse> LogoutAsync(WebcreteAPIExplorer.WebcreteAPI2.TicketHeader TicketHeader) {
            WebcreteAPIExplorer.WebcreteAPI2.LogoutRequest inValue = new WebcreteAPIExplorer.WebcreteAPI2.LogoutRequest();
            inValue.TicketHeader = TicketHeader;
            return ((WebcreteAPIExplorer.WebcreteAPI2.WebcreteAPISoap)(this)).LogoutAsync(inValue);
        }
    }
}
