//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebcreteAPIExplorer.WebcreteAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.concretego.com/", ConfigurationName="WebcreteAPI.WebcreteAPISoap")]
    public interface WebcreteAPISoap {
        
        // CODEGEN: Generating message contract since message GetPublicKeyResponse has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/GetPublicKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebcreteAPIExplorer.WebcreteAPI.GetPublicKeyResponse GetPublicKey(WebcreteAPIExplorer.WebcreteAPI.GetPublicKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/GetPublicKey", ReplyAction="*")]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI.GetPublicKeyResponse> GetPublicKeyAsync(WebcreteAPIExplorer.WebcreteAPI.GetPublicKeyRequest request);
        
        // CODEGEN: Generating message contract since message LoginRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebcreteAPIExplorer.WebcreteAPI.LoginResponse Login(WebcreteAPIExplorer.WebcreteAPI.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI.LoginResponse> LoginAsync(WebcreteAPIExplorer.WebcreteAPI.LoginRequest request);
        
        // CODEGEN: Generating message contract since message Login2Request has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/Login2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebcreteAPIExplorer.WebcreteAPI.Login2Response Login2(WebcreteAPIExplorer.WebcreteAPI.Login2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/Login2", ReplyAction="*")]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI.Login2Response> Login2Async(WebcreteAPIExplorer.WebcreteAPI.Login2Request request);
        
        // CODEGEN: Generating message contract since message ProcessRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/ProcessRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebcreteAPIExplorer.WebcreteAPI.ProcessRequestResponse ProcessRequest(WebcreteAPIExplorer.WebcreteAPI.ProcessRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/ProcessRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI.ProcessRequestResponse> ProcessRequestAsync(WebcreteAPIExplorer.WebcreteAPI.ProcessRequestRequest request);
        
        // CODEGEN: Generating message contract since message LogoutRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebcreteAPIExplorer.WebcreteAPI.LogoutResponse Logout(WebcreteAPIExplorer.WebcreteAPI.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.concretego.com/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI.LogoutResponse> LogoutAsync(WebcreteAPIExplorer.WebcreteAPI.LogoutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.concretego.com/")]
    public partial class TicketHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid ticketField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
                this.RaisePropertyChanged("ticket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPublicKey", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class GetPublicKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public string appID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=1)]
        public string apiKey;
        
        public GetPublicKeyRequest() {
        }
        
        public GetPublicKeyRequest(string appID, string apiKey) {
            this.appID = appID;
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPublicKeyResponse", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class GetPublicKeyResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.concretego.com/")]
        public WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public string GetPublicKeyResult;
        
        public GetPublicKeyResponse() {
        }
        
        public GetPublicKeyResponse(WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader, string GetPublicKeyResult) {
            this.TicketHeader = TicketHeader;
            this.GetPublicKeyResult = GetPublicKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.concretego.com/")]
        public WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=2)]
        public string slug;
        
        public LoginRequest() {
        }
        
        public LoginRequest(WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader, string userName, byte[] password, string slug) {
            this.TicketHeader = TicketHeader;
            this.userName = userName;
            this.password = password;
            this.slug = slug;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public bool LoginResult;
        
        public LoginResponse() {
        }
        
        public LoginResponse(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login2", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class Login2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.concretego.com/")]
        public WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=2)]
        public string slug;
        
        public Login2Request() {
        }
        
        public Login2Request(WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader, string userName, string password, string slug) {
            this.TicketHeader = TicketHeader;
            this.userName = userName;
            this.password = password;
            this.slug = slug;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login2Response", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class Login2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public bool Login2Result;
        
        public Login2Response() {
        }
        
        public Login2Response(bool Login2Result) {
            this.Login2Result = Login2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessRequest", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class ProcessRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.concretego.com/")]
        public WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public string request;
        
        public ProcessRequestRequest() {
        }
        
        public ProcessRequestRequest(WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader, string request) {
            this.TicketHeader = TicketHeader;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessRequestResponse", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class ProcessRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public string ProcessRequestResult;
        
        public ProcessRequestResponse() {
        }
        
        public ProcessRequestResponse(string ProcessRequestResult) {
            this.ProcessRequestResult = ProcessRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Logout", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.concretego.com/")]
        public WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader) {
            this.TicketHeader = TicketHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogoutResponse", WrapperNamespace="http://api.concretego.com/", IsWrapped=true)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.concretego.com/", Order=0)]
        public bool LogoutResult;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(bool LogoutResult) {
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebcreteAPISoapChannel : WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebcreteAPISoapClient : System.ServiceModel.ClientBase<WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap>, WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap {
        
        public WebcreteAPISoapClient() {
        }
        
        public WebcreteAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebcreteAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebcreteAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebcreteAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebcreteAPIExplorer.WebcreteAPI.GetPublicKeyResponse WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap.GetPublicKey(WebcreteAPIExplorer.WebcreteAPI.GetPublicKeyRequest request) {
            return base.Channel.GetPublicKey(request);
        }
        
        public WebcreteAPIExplorer.WebcreteAPI.TicketHeader GetPublicKey(string appID, string apiKey, out string GetPublicKeyResult) {
            WebcreteAPIExplorer.WebcreteAPI.GetPublicKeyRequest inValue = new WebcreteAPIExplorer.WebcreteAPI.GetPublicKeyRequest();
            inValue.appID = appID;
            inValue.apiKey = apiKey;
            WebcreteAPIExplorer.WebcreteAPI.GetPublicKeyResponse retVal = ((WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap)(this)).GetPublicKey(inValue);
            GetPublicKeyResult = retVal.GetPublicKeyResult;
            return retVal.TicketHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI.GetPublicKeyResponse> WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap.GetPublicKeyAsync(WebcreteAPIExplorer.WebcreteAPI.GetPublicKeyRequest request) {
            return base.Channel.GetPublicKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI.GetPublicKeyResponse> GetPublicKeyAsync(string appID, string apiKey) {
            WebcreteAPIExplorer.WebcreteAPI.GetPublicKeyRequest inValue = new WebcreteAPIExplorer.WebcreteAPI.GetPublicKeyRequest();
            inValue.appID = appID;
            inValue.apiKey = apiKey;
            return ((WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap)(this)).GetPublicKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebcreteAPIExplorer.WebcreteAPI.LoginResponse WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap.Login(WebcreteAPIExplorer.WebcreteAPI.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader, string userName, byte[] password, string slug) {
            WebcreteAPIExplorer.WebcreteAPI.LoginRequest inValue = new WebcreteAPIExplorer.WebcreteAPI.LoginRequest();
            inValue.TicketHeader = TicketHeader;
            inValue.userName = userName;
            inValue.password = password;
            inValue.slug = slug;
            WebcreteAPIExplorer.WebcreteAPI.LoginResponse retVal = ((WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap)(this)).Login(inValue);
            return retVal.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI.LoginResponse> WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap.LoginAsync(WebcreteAPIExplorer.WebcreteAPI.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI.LoginResponse> LoginAsync(WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader, string userName, byte[] password, string slug) {
            WebcreteAPIExplorer.WebcreteAPI.LoginRequest inValue = new WebcreteAPIExplorer.WebcreteAPI.LoginRequest();
            inValue.TicketHeader = TicketHeader;
            inValue.userName = userName;
            inValue.password = password;
            inValue.slug = slug;
            return ((WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebcreteAPIExplorer.WebcreteAPI.Login2Response WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap.Login2(WebcreteAPIExplorer.WebcreteAPI.Login2Request request) {
            return base.Channel.Login2(request);
        }
        
        public bool Login2(WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader, string userName, string password, string slug) {
            WebcreteAPIExplorer.WebcreteAPI.Login2Request inValue = new WebcreteAPIExplorer.WebcreteAPI.Login2Request();
            inValue.TicketHeader = TicketHeader;
            inValue.userName = userName;
            inValue.password = password;
            inValue.slug = slug;
            WebcreteAPIExplorer.WebcreteAPI.Login2Response retVal = ((WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap)(this)).Login2(inValue);
            return retVal.Login2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI.Login2Response> WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap.Login2Async(WebcreteAPIExplorer.WebcreteAPI.Login2Request request) {
            return base.Channel.Login2Async(request);
        }
        
        public System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI.Login2Response> Login2Async(WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader, string userName, string password, string slug) {
            WebcreteAPIExplorer.WebcreteAPI.Login2Request inValue = new WebcreteAPIExplorer.WebcreteAPI.Login2Request();
            inValue.TicketHeader = TicketHeader;
            inValue.userName = userName;
            inValue.password = password;
            inValue.slug = slug;
            return ((WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap)(this)).Login2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebcreteAPIExplorer.WebcreteAPI.ProcessRequestResponse WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap.ProcessRequest(WebcreteAPIExplorer.WebcreteAPI.ProcessRequestRequest request) {
            return base.Channel.ProcessRequest(request);
        }
        
        public string ProcessRequest(WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader, string request) {
            WebcreteAPIExplorer.WebcreteAPI.ProcessRequestRequest inValue = new WebcreteAPIExplorer.WebcreteAPI.ProcessRequestRequest();
            inValue.TicketHeader = TicketHeader;
            inValue.request = request;
            WebcreteAPIExplorer.WebcreteAPI.ProcessRequestResponse retVal = ((WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap)(this)).ProcessRequest(inValue);
            return retVal.ProcessRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI.ProcessRequestResponse> WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap.ProcessRequestAsync(WebcreteAPIExplorer.WebcreteAPI.ProcessRequestRequest request) {
            return base.Channel.ProcessRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI.ProcessRequestResponse> ProcessRequestAsync(WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader, string request) {
            WebcreteAPIExplorer.WebcreteAPI.ProcessRequestRequest inValue = new WebcreteAPIExplorer.WebcreteAPI.ProcessRequestRequest();
            inValue.TicketHeader = TicketHeader;
            inValue.request = request;
            return ((WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap)(this)).ProcessRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebcreteAPIExplorer.WebcreteAPI.LogoutResponse WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap.Logout(WebcreteAPIExplorer.WebcreteAPI.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public bool Logout(WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader) {
            WebcreteAPIExplorer.WebcreteAPI.LogoutRequest inValue = new WebcreteAPIExplorer.WebcreteAPI.LogoutRequest();
            inValue.TicketHeader = TicketHeader;
            WebcreteAPIExplorer.WebcreteAPI.LogoutResponse retVal = ((WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap)(this)).Logout(inValue);
            return retVal.LogoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI.LogoutResponse> WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap.LogoutAsync(WebcreteAPIExplorer.WebcreteAPI.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebcreteAPIExplorer.WebcreteAPI.LogoutResponse> LogoutAsync(WebcreteAPIExplorer.WebcreteAPI.TicketHeader TicketHeader) {
            WebcreteAPIExplorer.WebcreteAPI.LogoutRequest inValue = new WebcreteAPIExplorer.WebcreteAPI.LogoutRequest();
            inValue.TicketHeader = TicketHeader;
            return ((WebcreteAPIExplorer.WebcreteAPI.WebcreteAPISoap)(this)).LogoutAsync(inValue);
        }
    }
}
